### ISSUE TITLE
how to add Item to RoaringBitmap?

### ISSUE THREAD

**Issue by sgf** [Tornhoof/RoaringBitmap#10]
how to add Item to RoaringBitmap?
there only Create
cant find Add Api

**Comment by Tornhoof** [comment]
A bitmap is not an collection in the general .net sense, there is no Add API.
The API is based on the assumption that you have more or less immutable bitmaps (e.g. from disk etc.) which you create and then you operate via bitwise operations on it.
See: https://github.com/Tornhoof/RoaringBitmap/blob/master/RoaringBitmap.Tests/RoaringBitmapTests.cs for examples on how to do bitwise operations.

**Comment by sgf** [comment]
but the RoaringBitmap java project has Add Api

https://github.com/RoaringBitmap/RoaringBitmap#code-sample

> A bitmap is not an collection in the general .net sense, there is no Add API.
> The API is based on the assumption that you have more or less immutable bitmaps (e.g. from disk etc.) which you create and then you operate via bitwise operations on it.
> See: https://github.com/Tornhoof/RoaringBitmap/blob/master/RoaringBitmap.Tests/RoaringBitmapTests.cs for examples on how to do bitwise operations.
