### ISSUE TITLE
Work with Int64

### ISSUE THREAD

**Issue by phnx47** [Tornhoof/RoaringBitmap#2]
How I can work with Int64? Maybe have quick way to upgrade my code for Int64?

**Comment by Tornhoof** [comment]
I'm afraid there is no easy way to support Int64. Prof. Lemire still has to publish his reference implementation for 64bit. I imagine that it is quite a bit of change necessary. Might even be a different concept. 
If you need a 64 bit Bitmap you can take a look at https://github.com/lemire/csharpewah which should support it.

**Comment by lemire** [comment]
I think it might be useful to link these issues...

https://github.com/RoaringBitmap/RoaringBitmap/issues/109

https://github.com/RoaringBitmap/CRoaring/issues/1

There has been work and there are Java prototypes supporting 64-bit integers... but there is nothing "battle tested" yet.

One thing people could do to help is to provide the use cases, benchmarks...

**Comment by Tornhoof** [comment]
Treemap of Bitmaps sounds interesting :)
That would work in c# too with a Dictionary.
You can then decide for your actual data, if you want to use the higher 32bit or the lower 32bit as key and use the other part as value in the bitmap.

**Comment by phnx47** [comment]
Thanks for information! At the moment, I created an array of 256 values, it is not very comfortable, but I will can solve my task.

**Comment by Tornhoof** [comment]
I'll close this as your solution is as good as it gets currently.
