### ISSUE TITLE
Cardinality of 'full' bitmap seems to be broken

### ISSUE THREAD

**Issue by ax0l0tl** [Tornhoof/RoaringBitmap#3]
I'm using RoaringBitmap to back a search index implementation in .NET. Performance and memory usage is really impressive. Thanks for your work!

I'm not very deep into the theory behind it, but I ran into a problem when working with 'full' bitmaps (all bits set). In my understanding bitmap represents a set of numbers in range [int.MinValue,int.MaxValue]. So Cardinality property of RoaringBitmap and RoaringArray should be of type long to be able to represent max cardinality of 2^32?

```
[Fact]
public void CardinalityOfFullSet()
{
    var full = ~Collections.Special.RoaringBitmap.Create();

    Assert.Equal(Math.Pow(2, 32), full.Cardinality);
}

[Fact]
public void SerializeFullSet()
{
    var full = ~Collections.Special.RoaringBitmap.Create();

    using (var ms = new MemoryStream())
    {
        Collections.Special.RoaringBitmap.Serialize(full, ms);
        ms.Position = 0;
        var rb2 = Collections.Special.RoaringBitmap.Deserialize(ms);
        Assert.Equal(full, rb2);
    }
}
```

Both above tests fail. In CardinalityOfFullSet cardinality is negative because of the unchecked add operation in internal constructor of RoaringArray. SerializeFullSet throws an OverflowException because in private constructor of RoaringArray the checked Linq Sum implementation is used.

I just changed Cardinality property types on RoaringArray and RoaringBitmap to long. Serialization now works but the resulting cardinality of full bitset is 4294901760 not 2^32=4294967296 as I would have expected.

**Comment by lemire** [comment]
You probably meant "cardinality" and not "cadinality". (typo)

**Comment by ax0l0tl** [comment]
Ups, of course...

**Comment by Tornhoof** [comment]
I'll take a look on the weekend

**Comment by lemire** [comment]
@Tornhoof 

Other implementations of Roaring support "run containers" which are useful for really dense bitmaps. It is a lot of work to implement, but one nice trick you could implement if you are in a hurry is just support for "full containers". That is a lazy week-end job.

**Comment by Tornhoof** [comment]
@ax0l0tl 
You're correct this is a bug and you were spot on with the linq sum. As for the resulting cardinality, there is actually another bug in the ~ operator which stops at ushort.maxvalue, meaning we only have 65535 bitmaps in array and not 65536, which then results in 4294901760. I added the tests you provided to the test base.

Thanks for the report.

**Comment by Tornhoof** [comment]
I've published a new version of the nuget package with the changes.

**Comment by ax0l0tl** [comment]
Cool, thanks for the quick reaction!

**Comment by Tornhoof** [comment]
Closing the issue as this is fixed.
