### ISSUE TITLE
Serialize/deserialize from/to the "standard" binary format

### ISSUE THREAD

**Issue by lemire** [Tornhoof/RoaringBitmap#5]
We have an "official" Roaring format specification that this library should be able to at least partially support...

https://github.com/RoaringBitmap/RoaringFormatSpec

**Comment by Tornhoof** [comment]
The 'official' Roaring file format is supported with the release of https://www.nuget.org/packages/RoaringBitmap/0.0.9
It replaces the previous file format.
Both test files are serialized/deserialized just fine.

**Comment by lemire** [comment]
@Tornhoof  Fantastic. Then I guess we can close this issue?
