### ISSUE TITLE
Best way of querying large set of bitmaps

### ISSUE THREAD

**Issue by nhaberl** [Tornhoof/RoaringBitmap#8]
Hi,

could you explain what would be the best way to search through millions of Bitmaps for a given patter ?
Let's say each Bitmap is identified by an ID ... 

Thanks a lot

**Comment by Tornhoof** [comment]
I'm not certain that I follow, do you have millions of bitmaps or do you have millions of Ids and what exactly do you mean with a pattern? I guess you need to explain your use case a bit more.
Millions of bitmaps aren't really the use case of this library.
It is designed to create a bitset of e.g. integer ids, like database row ids and then you perform bitset operations (and,or, xor etc.)  on it.
Example:
You have one bitset with all document ids of documents containing the word 'Hello' and another bitset with all document ids of documents containing the word 'World'. A bitwise 'and' of both, then produces a bitset with all documents containing both words.

**Comment by nhaberl** [comment]
Oh I see ... I was thinking the way around ... 
What I wanted to say is that I have millions of documents and each of them is represented as a Bitmap where the bits are words which are in the document. When querying I set a bitmap of the words which I wanna find and AND them each.

But what you describe is an inverted index style where each word represents a bitmap which makes absolutely sense because I never look for more than 10 words at once so the iterations doens't matter otherwise I have to do a lot of iterations.

So I guess it makes sense to build a dictionary of bitmaps by word

**Comment by Tornhoof** [comment]
Yes the inverted index is a common concept for search engines.

**Comment by nhaberl** [comment]
I know, but I thought only of BTrees ... so main porinciples remain the same here also.
